image:
  repository: mysql
  tag: "latest"
  pullPolicy: IfNotPresent

mysqlRootPassword: "password123$"

pvc:
  accessModes:
    - ReadWriteMany
  storage: 1Gi

service:
  port: 3306

initScript: |
  CREATE DATABASE IF NOT EXISTS mydatabase;
  USE mydatabase;

  CREATE TABLE IF NOT EXISTS people (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      age INT NOT NULL
  );

  INSERT INTO people (name, age) VALUES ('Alice', FLOOR(21 + RAND() * 60));
  INSERT INTO people (name, age) VALUES ('Bob', FLOOR(21 + RAND() * 60));
  INSERT INTO people (name, age) VALUES ('Charlie', FLOOR(21 + RAND() * 60));
  INSERT INTO people (name, age) VALUES ('Jimmy', FLOOR(21 + RAND() * 60));
  INSERT INTO people (name, age) VALUES ('Candy', FLOOR(21 + RAND() * 60));
  INSERT INTO people (name, age) VALUES ('Fox', FLOOR(21 + RAND() * 60));
  INSERT INTO people (name, age) VALUES ('Test', FLOOR(21 + RAND() * 60));

  ALTER USER 'root'@'%' IDENTIFIED WITH 'mysql_native_password' BY 'password123$';
  FLUSH PRIVILEGES;
